### PR TITLE
chore: add package-lock.json

### PR DESCRIPTION
**Pull request by alexander-fenster**
As discussed with the team, let's commit `package-lock.json`.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Where was the discussion? I’m actually opposed to these for library development, as they can hide dependencies that come to introduce bugs. Locking down to specific “known to work” version isn’t reality for our users.

**Comment by alexander-fenster** [comment]
Unfortunately it was in the internal group :(  @ofrobots can comment here as well.

The rationale for the change is:
- `package-lock.json` is not packaged to npm so users won't really notice anything;
- having `package-lock.json` checked in simplifies development;
- we'll have nightly builds later this week and they will be run with `--no-package-lock` to make sure we get the same behavior as our users have.

**Comment by stephenplusplus** [comment]
The cron part is good, but what are the pros? How does it simplify development?

**Comment by alexander-fenster** [comment]
It has no benefits (and no harm as well) for 100% generated libraries. For manual libraries, the main benefit is that it makes sure all developers and CI work with the same versions of packages (will be especially useful when we stop supporting node4 in April, as node4 npm does not support `package-lock.json`).

**Comment by stephenplusplus** [comment]
Just linking this where we talked it over before: https://github.com/stephenplusplus/gcp-metadata/pull/18

**Comment by stephenplusplus** [comment]
But wouldn't it be better for the local developer to catch if there was a problem right away? Theoretically, they could fix for it before the cron job even ran. I've never considered protecting developers more important than protecting users.

**Comment by ofrobots** [comment]
>  I’m actually opposed to these for library development, as they can hide dependencies that come to introduce bugs. Locking down to specific “known to work” version isn’t reality for our users.

The problem you mention is there even without a `package-lock.json`. Our dependencies can change at any time, but they only get tested when there is a PR. PRs are rare.

What you are pointing out is that we need to do 'integration testing' against our dependencies. The proper way to do this is through cron based builds rather than PR builds. A good build focusses on one change at a time. PR builds should focus on just he PR – that is, no deps changes allowed. Integration builds should focus on just the dependencies – no local changes, or PRs should be present.

> How does it simplify development?

package-lock is for developers. It de-flakes the CI. When you run a build, you will the same behavior as I see. It isolates PRs – stuff that is changing – as the unique thing that gets tested by the CI. More opinions on this here: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/.

> But wouldn't it be better for the local developer to catch if there was a problem right away

Dependencies can be updated at any time. If it is really important to catch them right a way, then the cron job should run at a higher frequency.

As a developer if I am fixing a bug, I should not be derailed by a CI failure unrelated to my change. So no, developers, or contributors should not have the responsibility of catching unrelated breakages as part of active development.

**Comment by stephenplusplus** [comment]
> Our dependencies can change at any time, but they only get tested when there is a PR. 

As well as during development. For example, I'm in many of our repos each day. This would hide problems to "protect" me. I work here-- I want to know when I need to fix what we're making, so users don't have to let us know about it. Sure, if we run a lot of cron jobs, we'll be covered way better than just me, and I would definitely prefer that. However, we still don't have one at all, so we don't know if it works yet.

> A good build focusses on one change at a time. PR builds should focus on just he PR – that is, no deps changes allowed. Integration builds should focus on just the dependencies – no local changes, or PRs should be present.

The purity of CI and protecting developers from surprises isn't my main goal with a library, when it pushes those surprises to the user. But, this is probably where my philosophy will part ways from what you're saying is the collective's, in regards to those who were part of the internal discussion. I respect that I don't work singularly on this project, so I'm happy to put my differences aside and save them for my own projects.

**Comment by ofrobots** [comment]
>  However, we still don't have one at all, so we don't know if it works yet.

So let's try it and see if it does.

> I respect that I don't work singularly on this project, so I'm happy to put my differences aside and save them for my own projects.

You make more contributions to these libraries than anyone else, so your opinion is tremendously important here, and to me!

> The purity of CI and protecting developers from surprises isn't my main goal with a library, when it pushes those surprises to the user.

Note that the surprises are already being pushed to the user unless you are able to open PRs at a frequency of at least one per day on each repo. 

My contention is that with a cron job, you will get the feedback and surprises won't be pushed to users. What frequency would you like?

**Comment by stephenplusplus** [comment]
> You make more contributions to these libraries than anyone else, so your opinion is tremendously important here, and to me!

Thank you, and likewise, I highly trust your views on how to write a secure, performant, i.e. "correct", top-to-bottom Node.js module.

> My contention is that with a cron job, you will get the feedback and surprises won't be pushed to users.

I definitely like cron jobs. I think it's a case of "the more, the better", but a minimum of 1/day sounds like a good start. I'm curious to see how it will actually work:

- will we get false negatives, where CI is to blame?
- how will we be alerted when there is a failure?
- will we surpass our queue?

Automation always sounds good, but it's easy to end up spending more time fixing a CI script than it would be to manually do the same task. Even Circle lets us down quite often (random permissions errors running our test scripts), and Greenkeeper, it's part of my morning routine to close *multiple* erroneous issues saying our library is broken!

Considering that, I would prefer to wait to see the real-life behavior of the cron job before merging the package-lock.json changes.

(Linking for reference: https://github.com/GoogleCloudPlatform/google-cloud-common/issues/222)

**Comment by ofrobots** [comment]
> Automation always sounds good, but it's easy to end up spending more time fixing a CI script than it would be to manually do the same task. Even Circle lets us down quite often (random permissions errors running our test scripts).

Flaky builds are bad indeed. Independently of this discussion it sounds like it is worthwhile investing time to make sure we do not have random permission errors for example. I ran into it on one of [my PRs](https://github.com/googleapis/nodejs-logging-winston/pull/58) yesterday, and it was quite frustrating. Is there a central tracking issue for this?

Regardless, if flakiness exists, it can happen on a PR, or it can happen on a cron-based build. We are no worse off by having a cron based build.

Internally at Google there is a strong culture of investing time and effort to ensure builds are not flaky, so I am going to be supportive of prioritizing work to go fix flakiness.

**Comment by alexander-fenster** [comment]
As discussed with @stephenplusplus, we'll first have nightly builds running, and then will commit `package-lock.json` everywhere.

**Comment by stephenplusplus** [comment]
Workflow question: When will the `package-lock.json` in the repo be updated?

**Comment by stephenplusplus** [comment]
> Is there a central tracking issue for this?

@alexander-fenster I think you or @jmdobry were looking into the famous "sh: permission denied" / pipefail error.

> Regardless, if flakiness exists, it can happen on a PR, or it can happen on a cron-based build. We are no worse off by having a cron based build.

I would say we are worse off because if the cron doesn't work, then there is nothing left to catch dependency breakages but users. We're saying the same thing, that CI flakiness should be eliminated, but I'm adding the precondition that it should be de-flaked before we rely on it to catch breakages. (Or at least, test it out to see if flakiness will even be a big issue)

**Comment by alexander-fenster** [comment]
Already done by #19.

**Pull request closed without merging**
